import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/Global/ThemeProvider";
import Index from "./page";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import NewsLayer from "@/components/Global/NewsLayer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Local Server 3000",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {/* Home Page Component file import here*/}

       

          <Header />

          {children}
          <Footer/>
          <NewsLayer/>
        
      </ThemeProvider>
    </body>
    </html >
  );
}
